'use client';

import { logger } from '@/lib/logger';
import { useQueryClient } from '@tanstack/react-query';
import { ArrowLeft, Loader2 } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { useState } from 'react';
import { toast } from 'sonner';

import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import {
  itemsService,
  productsService,
  variantsService,
} from '@/services/stock';

import {
  StepProduct,
  StepStock,
  StepTemplate,
  StepVariants,
  useWizard,
  WizardStepper,
} from './src';

export default function ProductWizardPage() {
  const router = useRouter();
  const queryClient = useQueryClient();
  const [showExitDialog, setShowExitDialog] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [errors, setErrors] = useState<Record<string, string>>({});

  const {
    currentStep,
    data,
    canGoBack,
    isLastStep,
    goToStep,
    goBack,
    goForward,
    setTemplate,
    setProductData,
    addVariant,
    updateVariant,
    removeVariant,
    generateVariantsFromAttributes,
    updateStockEntry,
    validate,
    getCompletedSteps,
  } = useWizard();

  // Validation on step change
  const handleGoForward = () => {
    const validationErrors = validate();
    if (Object.keys(validationErrors).length > 0) {
      setErrors(validationErrors);
      return;
    }
    setErrors({});
    goForward();
  };

  // Submit wizard
  const handleSubmit = async () => {
    const validationErrors = validate();
    if (Object.keys(validationErrors).length > 0) {
      setErrors(validationErrors);
      return;
    }

    if (!data.product || !data.template) {
      setErrors({ general: 'Dados incompletos' });
      return;
    }

    setIsSubmitting(true);
    setErrors({});

    try {
      // 1. Create product
      const productPayload = {
        templateId: data.template.id,
        name: data.product.name,
        // fullCode is auto-generated by backend - not sent in create request
        description: data.product.description,
        attributes: data.product.attributes,
        manufacturerId: data.product.manufacturerId,
        supplierId: data.product.supplierId,
      };

      const createdProductResponse =
        await productsService.createProduct(productPayload);
      const createdProduct = createdProductResponse.product;

      // 2. Create variants
      const variantPromises = data.variants.map(variant =>
        variantsService.createVariant({
          productId: createdProduct.id,
          name: variant.name,
          sku: variant.sku,
          barcode: variant.barcode,
          price: variant.price,
          costPrice: variant.costPrice,
          attributes: variant.attributes,
        })
      );

      const createdVariantResponses = await Promise.all(variantPromises);
      const createdVariants = createdVariantResponses.map(r => r.variant);

      // 3. Create initial stock items
      const stockPromises: Promise<unknown>[] = [];

      for (let i = 0; i < createdVariants.length; i++) {
        const variant = createdVariants[i];
        const originalVariant = data.variants[i];
        const stockEntry = data.stockEntries.find(
          e => e.variantId === originalVariant.id
        );

        if (stockEntry && stockEntry.quantity && stockEntry.quantity > 0) {
          // Create items for initial stock
          stockPromises.push(
            itemsService.createBatch({
              variantId: variant.id,
              locationId: stockEntry.locationId,
              quantity: stockEntry.quantity,
              lotNumber: stockEntry.lotNumber,
              expirationDate: stockEntry.expirationDate,
              movementType: 'ENTRY',
              movementReason: 'Cadastro inicial via wizard',
            })
          );
        }
      }

      if (stockPromises.length > 0) {
        await Promise.all(stockPromises);
      }

      // Invalidate queries
      queryClient.invalidateQueries({ queryKey: ['products'] });
      queryClient.invalidateQueries({ queryKey: ['variants'] });
      queryClient.invalidateQueries({ queryKey: ['items'] });
      queryClient.invalidateQueries({ queryKey: ['analytics'] });

      toast.success('Produto cadastrado com sucesso!', {
        description: `${data.variants.length} variante(s) e estoque inicial criados.`,
      });

      // Navigate to product detail
      router.push(`/stock/products/${createdProduct.id}`);
    } catch (error) {
      logger.error(
        'Wizard submit error',
        error instanceof Error ? error : undefined
      );
      toast.error('Erro ao cadastrar produto', {
        description:
          error instanceof Error ? error.message : 'Erro desconhecido',
      });
    } finally {
      setIsSubmitting(false);
    }
  };

  // Handle exit
  const handleExit = () => {
    const hasData =
      data.template || data.product?.name || data.variants.length > 0;

    if (hasData) {
      setShowExitDialog(true);
    } else {
      router.back();
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center gap-4">
        <Button
          variant="ghost"
          size="icon"
          onClick={handleExit}
          aria-label="Voltar"
        >
          <ArrowLeft className="h-5 w-5" />
        </Button>
        <div>
          <h1 className="text-2xl font-bold tracking-tight">
            Cadastro de Produto
          </h1>
          <p className="text-muted-foreground">
            Assistente para cadastrar produtos, variantes e estoque inicial
          </p>
        </div>
      </div>

      {/* Stepper */}
      <WizardStepper
        currentStep={currentStep}
        completedSteps={getCompletedSteps()}
        onStepClick={goToStep}
      />

      {/* Content */}
      <Card>
        <CardContent className="pt-6">
          {currentStep === 'template' && (
            <StepTemplate
              selectedTemplate={data.template}
              onSelect={setTemplate}
              errors={errors}
            />
          )}

          {currentStep === 'product' && data.template && (
            <StepProduct
              template={data.template}
              initialData={data.product}
              onChange={setProductData}
              errors={errors}
            />
          )}

          {currentStep === 'variants' && data.template && (
            <StepVariants
              template={data.template}
              productName={data.product?.name || ''}
              variants={data.variants}
              onAddVariant={addVariant}
              onUpdateVariant={updateVariant}
              onRemoveVariant={removeVariant}
              onGenerateVariants={generateVariantsFromAttributes}
              errors={errors}
            />
          )}

          {currentStep === 'stock' && (
            <StepStock
              variants={data.variants}
              stockEntries={data.stockEntries}
              onUpdateStockEntry={updateStockEntry}
              errors={errors}
            />
          )}
        </CardContent>
      </Card>

      {/* Navigation */}
      <div className="flex items-center justify-between">
        <Button
          variant="outline"
          onClick={goBack}
          disabled={!canGoBack || isSubmitting}
        >
          Voltar
        </Button>

        <div className="flex gap-2">
          <Button variant="ghost" onClick={handleExit} disabled={isSubmitting}>
            Cancelar
          </Button>

          {isLastStep ? (
            <Button onClick={handleSubmit} disabled={isSubmitting}>
              {isSubmitting && (
                <Loader2 className="h-4 w-4 mr-2 animate-spin" />
              )}
              Finalizar Cadastro
            </Button>
          ) : (
            <Button onClick={handleGoForward}>Próximo</Button>
          )}
        </div>
      </div>

      {/* Exit Confirmation Dialog */}
      <AlertDialog open={showExitDialog} onOpenChange={setShowExitDialog}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Descartar alterações?</AlertDialogTitle>
            <AlertDialogDescription>
              Você tem dados não salvos. Se sair agora, todas as informações
              inseridas serão perdidas.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Continuar editando</AlertDialogCancel>
            <AlertDialogAction
              onClick={() => router.back()}
              className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
            >
              Descartar e sair
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}
