/**
 * OpenSea OS - Stock Permissions Constants
 *
 * Proxy de conveniência sobre os códigos centrais em permission-codes.ts.
 * Mantém a API antiga (LIST, VIEW, CREATE, UPDATE, DELETE, MANAGE, EXPORT, IMPORT)
 * mapeando para as novas ações (ACCESS, REGISTER, MODIFY, REMOVE, ADMIN, EXPORT, IMPORT).
 */

import { STOCK_PERMISSIONS as STOCK_CODES } from '@/config/rbac/permission-codes';

export const STOCK_PERMISSIONS = {
  PRODUCTS: {
    LIST: STOCK_CODES.PRODUCTS.ACCESS,
    VIEW: STOCK_CODES.PRODUCTS.ACCESS,
    CREATE: STOCK_CODES.PRODUCTS.REGISTER,
    UPDATE: STOCK_CODES.PRODUCTS.MODIFY,
    DELETE: STOCK_CODES.PRODUCTS.REMOVE,
    EXPORT: STOCK_CODES.PRODUCTS.EXPORT,
    IMPORT: STOCK_CODES.PRODUCTS.IMPORT,
    MANAGE: STOCK_CODES.PRODUCTS.ADMIN,
  },

  VARIANTS: {
    LIST: STOCK_CODES.VARIANTS.ACCESS,
    VIEW: STOCK_CODES.VARIANTS.ACCESS,
    CREATE: STOCK_CODES.VARIANTS.REGISTER,
    UPDATE: STOCK_CODES.VARIANTS.MODIFY,
    DELETE: STOCK_CODES.VARIANTS.REMOVE,
    EXPORT: STOCK_CODES.VARIANTS.EXPORT,
    IMPORT: STOCK_CODES.VARIANTS.IMPORT,
    MANAGE: STOCK_CODES.VARIANTS.ADMIN,
  },

  ITEMS: {
    LIST: STOCK_CODES.ITEMS.ACCESS,
    VIEW: STOCK_CODES.ITEMS.ACCESS,
    CREATE: STOCK_CODES.ITEMS.ACCESS,
    UPDATE: STOCK_CODES.ITEMS.ACCESS,
    DELETE: STOCK_CODES.ITEMS.ADMIN,
    EXPORT: STOCK_CODES.ITEMS.EXPORT,
    MANAGE: STOCK_CODES.ITEMS.ADMIN,
  },

  TEMPLATES: {
    LIST: STOCK_CODES.TEMPLATES.ACCESS,
    VIEW: STOCK_CODES.TEMPLATES.ACCESS,
    CREATE: STOCK_CODES.TEMPLATES.REGISTER,
    UPDATE: STOCK_CODES.TEMPLATES.MODIFY,
    DELETE: STOCK_CODES.TEMPLATES.REMOVE,
    MANAGE: STOCK_CODES.TEMPLATES.REMOVE,
  },

  CATEGORIES: {
    LIST: STOCK_CODES.CATEGORIES.ACCESS,
    VIEW: STOCK_CODES.CATEGORIES.ACCESS,
    CREATE: STOCK_CODES.CATEGORIES.REGISTER,
    UPDATE: STOCK_CODES.CATEGORIES.MODIFY,
    DELETE: STOCK_CODES.CATEGORIES.REMOVE,
    IMPORT: STOCK_CODES.CATEGORIES.IMPORT,
    EXPORT: STOCK_CODES.CATEGORIES.EXPORT,
    MANAGE: STOCK_CODES.CATEGORIES.REMOVE,
  },

  MANUFACTURERS: {
    LIST: STOCK_CODES.MANUFACTURERS.ACCESS,
    VIEW: STOCK_CODES.MANUFACTURERS.ACCESS,
    CREATE: STOCK_CODES.MANUFACTURERS.REGISTER,
    UPDATE: STOCK_CODES.MANUFACTURERS.MODIFY,
    DELETE: STOCK_CODES.MANUFACTURERS.REMOVE,
    IMPORT: STOCK_CODES.MANUFACTURERS.IMPORT,
    EXPORT: STOCK_CODES.MANUFACTURERS.EXPORT,
    MANAGE: STOCK_CODES.MANUFACTURERS.REMOVE,
  },

  LOCATIONS: {
    LIST: STOCK_CODES.WAREHOUSES.ACCESS,
    VIEW: STOCK_CODES.WAREHOUSES.ACCESS,
    CREATE: STOCK_CODES.WAREHOUSES.REGISTER,
    UPDATE: STOCK_CODES.WAREHOUSES.MODIFY,
    DELETE: STOCK_CODES.WAREHOUSES.REMOVE,
    MANAGE: STOCK_CODES.WAREHOUSES.ADMIN,
  },

  WAREHOUSES: {
    LIST: STOCK_CODES.WAREHOUSES.ACCESS,
    VIEW: STOCK_CODES.WAREHOUSES.ACCESS,
    CREATE: STOCK_CODES.WAREHOUSES.REGISTER,
    UPDATE: STOCK_CODES.WAREHOUSES.MODIFY,
    DELETE: STOCK_CODES.WAREHOUSES.REMOVE,
    MANAGE: STOCK_CODES.WAREHOUSES.ADMIN,
  },

  PURCHASE_ORDERS: {
    LIST: STOCK_CODES.PURCHASE_ORDERS.ACCESS,
    VIEW: STOCK_CODES.PURCHASE_ORDERS.ACCESS,
    CREATE: STOCK_CODES.PURCHASE_ORDERS.REGISTER,
    UPDATE: STOCK_CODES.PURCHASE_ORDERS.MODIFY,
    DELETE: STOCK_CODES.PURCHASE_ORDERS.REMOVE,
    EXPORT: STOCK_CODES.PURCHASE_ORDERS.EXPORT,
    MANAGE: STOCK_CODES.PURCHASE_ORDERS.ADMIN,
  },

  VOLUMES: {
    LIST: STOCK_CODES.VOLUMES.ACCESS,
    VIEW: STOCK_CODES.VOLUMES.ACCESS,
    CREATE: STOCK_CODES.VOLUMES.REGISTER,
    UPDATE: STOCK_CODES.VOLUMES.MODIFY,
    DELETE: STOCK_CODES.VOLUMES.REMOVE,
    EXPORT: STOCK_CODES.VOLUMES.EXPORT,
    MANAGE: STOCK_CODES.VOLUMES.ADMIN,
  },

  TAGS: {
    LIST: STOCK_CODES.PRODUCTS.ACCESS,
    VIEW: STOCK_CODES.PRODUCTS.ACCESS,
    CREATE: STOCK_CODES.PRODUCTS.REGISTER,
    UPDATE: STOCK_CODES.PRODUCTS.MODIFY,
    DELETE: STOCK_CODES.PRODUCTS.REMOVE,
    MANAGE: STOCK_CODES.PRODUCTS.ADMIN,
  },

  MOVEMENTS: {
    LIST: STOCK_CODES.ITEMS.ACCESS,
    VIEW: STOCK_CODES.ITEMS.ACCESS,
    EXPORT: STOCK_CODES.ITEMS.EXPORT,
  },

  PRINT: {
    BARCODES: STOCK_CODES.ITEMS.PRINT,
  },
} as const;

// Type exports
export type StockProductsPermission =
  (typeof STOCK_PERMISSIONS.PRODUCTS)[keyof typeof STOCK_PERMISSIONS.PRODUCTS];

export type StockVariantsPermission =
  (typeof STOCK_PERMISSIONS.VARIANTS)[keyof typeof STOCK_PERMISSIONS.VARIANTS];

export type StockItemsPermission =
  (typeof STOCK_PERMISSIONS.ITEMS)[keyof typeof STOCK_PERMISSIONS.ITEMS];

export type StockMovementsPermission =
  (typeof STOCK_PERMISSIONS.MOVEMENTS)[keyof typeof STOCK_PERMISSIONS.MOVEMENTS];

export type StockLocationsPermission =
  (typeof STOCK_PERMISSIONS.LOCATIONS)[keyof typeof STOCK_PERMISSIONS.LOCATIONS];

export type StockWarehousesPermission =
  (typeof STOCK_PERMISSIONS.WAREHOUSES)[keyof typeof STOCK_PERMISSIONS.WAREHOUSES];

export type StockTemplatesPermission =
  (typeof STOCK_PERMISSIONS.TEMPLATES)[keyof typeof STOCK_PERMISSIONS.TEMPLATES];

export type StockCategoriesPermission =
  (typeof STOCK_PERMISSIONS.CATEGORIES)[keyof typeof STOCK_PERMISSIONS.CATEGORIES];

export type StockManufacturersPermission =
  (typeof STOCK_PERMISSIONS.MANUFACTURERS)[keyof typeof STOCK_PERMISSIONS.MANUFACTURERS];

export type StockTagsPermission =
  (typeof STOCK_PERMISSIONS.TAGS)[keyof typeof STOCK_PERMISSIONS.TAGS];

export type StockPurchaseOrdersPermission =
  (typeof STOCK_PERMISSIONS.PURCHASE_ORDERS)[keyof typeof STOCK_PERMISSIONS.PURCHASE_ORDERS];

export type StockPermission =
  | StockProductsPermission
  | StockVariantsPermission
  | StockItemsPermission
  | StockMovementsPermission
  | StockLocationsPermission
  | StockWarehousesPermission
  | StockTemplatesPermission
  | StockCategoriesPermission
  | StockManufacturersPermission
  | StockTagsPermission
  | StockPurchaseOrdersPermission;

export default STOCK_PERMISSIONS;
